# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        UserBundle\Entity\User:
            id: encoder.md5sh1

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_db:
            entity: { class: UserBundle\Entity\User }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                default_target_path: home
                login_path:  /login
                check_path:  /login_check
            anonymous: ~

            logout:
                invalidate_session: false
                path:   auth_logout

    access_control:
        - { path: "^/login", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/signup", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/user/create", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/motorbikes", roles: ROLE_USER }